export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const INIT_INGRIDIENTS = 'INIT_INGRIDIENTS';
export const INIT_INGRIDIENTS_FAIL = 'INIT_INGRIDIENTS_FAIL';